Repository zairza-cetb/bench-routes, pull requests merged in 2020-03, with the labels that each got.

#166 Reduce redundancy in .tsx files #126 and fixed a flood ping button Bug.
  dashboard/v1.0/package-lock.json
  dashboard/v1.0/src/components/service-ui/FloodPing.tsx
  dashboard/v1.0/src/components/service-ui/Jitter.tsx
  dashboard/v1.0/src/components/service-ui/Ping.tsx
  dashboard/v1.0/src/components/service-ui/getChartOptions.ts
  dashboard/v1.0/src/components/service-ui/publicOpts.ts
  go.mod
  go.sum
Labels: gssoc20, medium

#172 Dashboard v1.1
  .travis.yml
  Makefile
  dashboard/v1.1/.eslintrc.json
  dashboard/v1.1/.gitignore
  dashboard/v1.1/.prettierrc.json
  dashboard/v1.1/INSTALL.md
  dashboard/v1.1/README.md
  dashboard/v1.1/package-lock.json
  dashboard/v1.1/package.json
  dashboard/v1.1/public/assets/css/bootstrap.min.css
  dashboard/v1.1/public/assets/icons/bench-icon.svg
  dashboard/v1.1/public/assets/icons/cross.svg
  dashboard/v1.1/public/assets/icons/dashboard-icon.svg
  dashboard/v1.1/public/assets/icons/flood-icon.png
  dashboard/v1.1/public/assets/icons/jitter-icon.png
  dashboard/v1.1/public/assets/icons/monitoring-icon.svg
  dashboard/v1.1/public/assets/icons/notify-icon.svg
  dashboard/v1.1/public/assets/icons/ping-meter.svg
  dashboard/v1.1/public/assets/icons/settings-icon.svg
  dashboard/v1.1/public/assets/icons/wall.png
  dashboard/v1.1/public/index.html
  dashboard/v1.1/public/robots.txt
  dashboard/v1.1/src/App.css
  dashboard/v1.1/src/App.test.tsx
  dashboard/v1.1/src/App.tsx
  dashboard/v1.1/src/index.css
  dashboard/v1.1/src/index.tsx
  dashboard/v1.1/src/react-app-env.d.ts
  dashboard/v1.1/src/serviceWorker.ts
  dashboard/v1.1/src/setupTests.ts
  dashboard/v1.1/tsconfig.json
Labels: discussion, priority:high

#179 Update Readme.md
  README.md
Labels: beginner, gssoc20

#181 Split BaseLayout into Nav and Sidebar
  dashboard/v1.1/src/layouts/BaseLayout.tsx
  dashboard/v1.1/src/layouts/Navbar.tsx
  dashboard/v1.1/src/layouts/Sidebar.tsx
Labels: enhancement, react-ui

#182 Release alpha-2
  dashboard/v1.0/package.json
  src/lib/api/api.go
  src/main.go
  ui-builds/v1.0/asset-manifest.json
  ui-builds/v1.0/assets/css/bootstrap.min.css
  ui-builds/v1.0/assets/icons/bench-icon.svg
  ui-builds/v1.0/assets/icons/cross.svg
  ui-builds/v1.0/assets/icons/dashboard-icon.svg
  ui-builds/v1.0/assets/icons/flood-icon.png
  ui-builds/v1.0/assets/icons/jitter-icon.png
  ui-builds/v1.0/assets/icons/monitoring-icon.svg
  ui-builds/v1.0/assets/icons/notify-icon.svg
  ui-builds/v1.0/assets/icons/ping-meter.svg
  ui-builds/v1.0/assets/icons/settings-icon.svg
  ui-builds/v1.0/assets/icons/wall.png
  ui-builds/v1.0/favicon.ico
  ui-builds/v1.0/index.html
  ui-builds/v1.0/main.js
  ui-builds/v1.0/manifest.json
  ui-builds/v1.0/precache-manifest.f72d75759ef80939a1fb860b4271d5ef.js
  ui-builds/v1.0/robots.txt
  ui-builds/v1.0/service-worker.js
  ui-builds/v1.0/static/css/main.c606b425.chunk.css
  ui-builds/v1.0/static/css/main.c606b425.chunk.css.map
  ui-builds/v1.0/static/js/2.3becdd9f.chunk.js
  ui-builds/v1.0/static/js/2.3becdd9f.chunk.js.map
  ui-builds/v1.0/static/js/main.827a8c16.chunk.js
  ui-builds/v1.0/static/js/main.827a8c16.chunk.js.map
  ui-builds/v1.0/static/js/runtime-main.bae1b5fb.js
  ui-builds/v1.0/static/js/runtime-main.bae1b5fb.js.map
  ui-builds/v1.0/static/media/wall.854fe018.png
Labels: priority:high
